import type { INodeProperties } from 'n8n-workflow';

export const imageOptions: INodeProperties = {
	displayName: 'Options',
	name: 'imageOptions',
	type: 'collection',
	placeholder: 'Add option',
	default: {},
	displayOptions: { show: { operation: ['image'] } },
	options: [
		{
			displayName: 'File Name',
			name: 'fileName',
			type: 'string',
			default: 'image.png',
			description: 'Name given to the generated image',
		},
		{
			displayName: 'Format',
			name: 'type',
			type: 'options',
			default: 'png',
			description: 'Image file format',
			options: [
				{ name: 'PNG', value: 'png' },
				{ name: 'JPEG', value: 'jpeg' },
			],
		},
		{
			displayName: 'Full Page',
			name: 'fullPage',
			type: 'boolean',
			default: true,
			description: 'Whether to capture the whole scrollable page rather than just the viewport',
		},
		{
			displayName: 'Height',
			name: 'height',
			type: 'number',
			default: 800,
			description: 'Viewport height in pixels',
		},
		{
			displayName: 'Pixel Density',
			name: 'deviceScaleFactor',
			type: 'number',
			typeOptions: { minValue: 1, maxValue: 4 },
			default: 2,
			description: 'Multiplier for the output resolution. 2 gives a retina-sharp image.',
		},
		{
			displayName: 'Put Output File in Field',
			name: 'binaryPropertyName',
			type: 'string',
			default: 'data',
			description: 'Name of the binary field to write the file to',
		},
		{
			displayName: 'Quality',
			name: 'quality',
			type: 'number',
			typeOptions: { minValue: 1, maxValue: 100 },
			default: 85,
			description: 'JPEG quality. Ignored for PNG.',
		},
		{
			displayName: 'Timeout (Ms)',
			name: 'timeout',
			type: 'number',
			typeOptions: { minValue: 1000, maxValue: 120000 },
			default: 30000,
			description: 'How long the renderer may spend on this image before giving up',
		},
		{
			displayName: 'Transparent Background',
			name: 'omitBackground',
			type: 'boolean',
			default: false,
			description: 'Whether to leave the page background transparent instead of white',
		},
		{
			displayName: 'Wait For',
			name: 'waitFor',
			type: 'string',
			default: '',
			placeholder: '2000  or  #chart-ready  or  networkidle',
			description: 'Wait before capturing: milliseconds, a CSS selector, or "networkidle"',
		},
		{
			displayName: 'Width',
			name: 'width',
			type: 'number',
			default: 1280,
			description: 'Viewport width in pixels',
		},
	],
};

export const mergeFields: INodeProperties[] = [
	{
		displayName: 'Merge',
		name: 'mergeSource',
		type: 'options',
		noDataExpression: true,
		default: 'items',
		description: 'Where the PDFs to merge come from',
		displayOptions: { show: { operation: ['merge'] } },
		options: [
			{
				name: 'All Input Items',
				value: 'items',
				description: 'Take one PDF from each incoming item and merge them in order. This runs once, not once per item.',
			},
			{
				name: 'List of URLs',
				value: 'urls',
				description: 'Merge PDFs downloaded from public URLs',
			},
		],
	},
	{
		displayName: 'Input Binary Field',
		name: 'mergeBinaryProperty',
		type: 'string',
		default: 'data',
		required: true,
		description: 'Binary field on each incoming item that holds the PDF',
		displayOptions: { show: { operation: ['merge'], mergeSource: ['items'] } },
	},
	{
		displayName: 'URLs',
		name: 'mergeUrls',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		required: true,
		placeholder: 'https://example.com/a.pdf\nhttps://example.com/b.pdf',
		description: 'One PDF URL per line, in the order they should appear',
		displayOptions: { show: { operation: ['merge'], mergeSource: ['urls'] } },
	},
	{
		displayName: 'Options',
		name: 'mergeOptions',
		type: 'collection',
		placeholder: 'Add option',
		default: {},
		displayOptions: { show: { operation: ['merge'] } },
		options: [
			{
				displayName: 'Put Output File in Field',
				name: 'binaryPropertyName',
				type: 'string',
				default: 'data',
				description: 'Name of the binary field to write the merged PDF to',
			},
			{
				displayName: 'Title',
				name: 'title',
				type: 'string',
				default: '',
				description: 'Title recorded in the merged PDF metadata',
			},
			{
				displayName: 'URL Expires After (Minutes)',
				name: 'expiresInMinutes',
				type: 'number',
				typeOptions: { minValue: 1, maxValue: 10080 },
				default: 60,
				description: 'How long a hosted URL stays valid. Only used when Output is Hosted URL.',
			},
		],
	},
];
